model_list:
  - model_name: llama-3-70b
    litellm_params:
      model: watsonx/meta-llama/llama-3-3-70b-instruct
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"

  - model_name: llama-3-8b
    litellm_params:
      model: watsonx/meta-llama/llama-3-1-8b-instruct
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"
      seed: 10

  - model_name: granite-8b 
    litellm_params:
      model: watsonx/ibm/granite-3-8b-instruct
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"

  - model_name: mistral-large
    litellm_params:
      model: watsonx/mistralai/mistral-large
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"

  - model_name: mixtral
    litellm_params:
      model: watsonx/mistralai/mixtral-8x7b-instruct-v01
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"

litellm_settings:
  telemetry: False
  add_function_to_prompt: True
